### ISSUE TITLE
Too many values to unpack error in consoleLabel, line 183, csvhelpers.py

### ISSUE THREAD

**Issue by aepton** [datamade/csvdedupe#33]
Getting an error here:

for field in set(field for field, compare in deduper.data_model.field_comparators):

Turns out the field_comparators list contains 4-tuple elements, not 2-tuples, so the fix should be something like:

for field in set(field for field, compare, unused_1, unused_2 in deduper.data_model.field_comparators):

**Comment by Chartres** [comment]
+1 on this one, turning the pair into a quadruple, i.e. replacing line 183 of csvhelpers.py with `for field in set(field for field, compare, unused_1, unused_2` as suggested by @aepton let me run successfully. BTW using dedupe version 0.8.0.0.8.
