### ISSUE TITLE
print() and input() statements not echoing to console

### ISSUE THREAD

**Issue by paulshannon** [datamade/csvdedupe#37]
When I run cvslink, I get the following output:

	INFO:root:Generating grammar tables from /usr/lib/python2.7/lib2to3/Grammar.txt
	INFO:root:Generating grammar tables from /usr/lib/python2.7/lib2to3/PatternGrammar.txt
	INFO:root:imported 9568 rows from file 1
	INFO:root:imported 6790 rows from file 2
	INFO:root:using fields: ['title', 'year', 'duration', 'director']
	INFO:root:taking a sample of 1500 possible pairs
	INFO:root:starting active labeling...
	INFO:dedupe.api:Learned Weights
	INFO:dedupe.api:('(title: String)', 8.127357362229678e-05)
	INFO:dedupe.api:('(year: String)', 8.127357362229678e-05)
	INFO:dedupe.api:('(duration: String)', 8.127357362229678e-05)
	INFO:dedupe.api:('(director: String)', -2.464518083101114e-05)
	INFO:dedupe.api:('bias', 16.064579514990712)
	INFO:dedupe.training:1.0

and the program is waiting for input at [`convenience.py:42`](https://github.com/datamade/dedupe/blob/64e33324c9e499ad735b9a75a27c2cd3bee5ab59/dedupe/convenience.py#L42). I think that the stdout is getting swallowed up somewhere but I can't track it down. I can throw a breakpoint in there and log additional output no problem but my print statements get swallowed up.

**Comment by fgregg** [comment]
Hmm... What's your operating system?

**Comment by paulshannon** [comment]
I'm running in it an Ubuntu VM.

**Comment by fgregg** [comment]
Oh, that's very strange. You have the latest version?

**Comment by fgregg** [comment]
Can you run the examples in the README?

**Comment by paulshannon** [comment]
Yup. I've tried with the repos from Pypi and from the github sources.

**Comment by paulshannon** [comment]
The examples are working.... hmmm....

**Comment by paulshannon** [comment]
My bad, problem between keyboard and chair.
