### ISSUE TITLE
UnicodeEncodeError when running 0.1.10

### ISSUE THREAD

**Issue by grssnbchr** [datamade/csvdedupe#42]
I'm using csvdedupe v0.1.10 on Ubuntu 12.04 (Python 2.7.11), installed via pip.

Consider test.csv, which is encoded in UTF-8 

```
"ID";"Name_ID";"Name";"Interessengruppe";"Branche";"Stiftung"
1;1;"Wiler Parkhaus AG";"Individualverkehr";"Energie, Umwelt & Mobilität";0
2;2;"Stefan Kölliker Treuhand & Unternehmensberatung";"Advokaturen/Treuhand";"Beratung, Advokatur, PR & Treuhand";0
3;3;"HB-Gruppe";"Investmentgesellschaften";"Finanzwirtschaft & Versicherungen";0
```

and dedupe_config.json

```
{
  "field_names": ["Name", "Interessengruppe", "Branche", "Stiftung"],
  "field_definitions" : [{"field" : "Name", "type" : "String"},
                        {"field" : "Interessengruppe", "type" : "String"},
                        {"field" : "Branche", "type" : "String"},
                        {"field" : "Stiftung", "type": "Categorical",
                        "categories" : ["0", "1"]}
                        ],
  "output_file": "examples/organisations_deduped.csv",
  "skip_training": false,
  "training_file": "training.json",
  "sample_size": 150000,
  "recall_weight": 2
}
```

Now, when running `csvdedupe --config_file dedupe_config.json test.csv, I get the following error: 
`UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 70: ordinal not in range(128)` 

`\xe4` corresponds to "ä" in "Mobilität" as far as I know.

I thought this should work with unicodecsv.
Thanks!

**Comment by grssnbchr** [comment]
In the meantime, I managed to convert all non-ASCII characters (>127) to ASCII by replacing them with "x" (I know there's probably a better way, e.g. replacing "ä" with "a"). The same file now looks like this: 

```
"ID";"Name_ID";"Name";"Interessengruppe";"Branche";"Stiftung"
1;1;"Wiler Parkhaus AG";"Individualverkehr";"Energie, Umwelt & Mobilitxxt";0
2;2;"Stefan Kxxlliker Treuhand & Unternehmensberatung";"Advokaturen/Treuhand";"Beratung, Advokatur, PR & Treuhand";0
3;3;"HB-Gruppe";"Investmentgesellschaften";"Finanzwirtschaft & Versicherungen";0
```

Not surprisingly, I don't get that error anymore.. but another one: 
```
Traceback (most recent call last):
  File "/home/tgrossen/anaconda2/bin/csvdedupe", line 11, in <module>
    sys.exit(launch_new_instance())
  File "/home/tgrossen/anaconda2/lib/python2.7/site-packages/csvdedupe/csvdedupe.py", line 162, in launch_new_instance
    d.main()
  File "/home/tgrossen/anaconda2/lib/python2.7/site-packages/csvdedupe/csvdedupe.py", line 67, in main
    data_d = csvhelpers.readData(self.input, self.field_names)
  File "/home/tgrossen/anaconda2/lib/python2.7/site-packages/csvdedupe/csvhelpers.py", line 53, in readData
    clean_row = [(k, preProcess(v)) for (k, v) in row.items()]
  File "/home/tgrossen/anaconda2/lib/python2.7/site-packages/csvdedupe/csvhelpers.py", line 29, in preProcess
    column = re.sub('  +', ' ', column)
  File "/home/tgrossen/anaconda2/lib/python2.7/re.py", line 155, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or buffer
```

**Comment by DaveKlassen4** [comment]
Last time I solved this I didn't really remember how I did it, so I was faced with the problem again today. From my research my problem surrounds a "latin-1" encoding and the character 0xE9 (é). Just for reference sake and anyone who would not like to remove the context specific value in their actual data... In my research I found you can use the iconv unix style program to convert to an acceptable format. For my own specific scenario I used this command:

    cat latin1.txt | iconv -f latin1 -t utf-8 > utf8.txt

If you run a diff command on the two files now you will now only see the difference in the lines converted. Another way to view the data is using "hexdump -C".

**Comment by rotsee** [comment]
I can confirm this bug for version `0.1.10`. Csvdedupe will not terminate with `UnicodeEncodeError` with non ascii characters in an utf-8 csv file:

>  ...
>   File "/usr/local/lib/python2.7/dist-packages/csvdedupe/csvhelpers.py", line 52, in readData
>    for i, row in enumerate(reader):
>  ...
>  UnicodeEncodeError: 'ascii' codec can't encode character ...

**Comment by grssnbchr** [comment]
Thank you! Nice presentation at #NICAR16 btw ;-)

**Comment by fgregg** [comment]
Thanks! I just ran into and fixed another unicode error for writing out the results.
