### ISSUE TITLE
Option to use previous settings file?

### ISSUE THREAD

**Issue by DaveKlassen4** [datamade/csvdedupe#45]
As I learn more about this set of scripts. I discovered there is quite a similar script to csvdedupe.py here:

    https://github.com/datamade/dedupe-examples/blob/master/csv_example/csv_example.py

Looking at this script I like one specific ability not present in the library version, and this is the ability to save and use in consecutive runs, the dedupe training settings file (used in the last run). Essentially I want to have results that are consistent (and likely be able to judge one run as more successful than another). Was this left out of this specific script with cause, or simply because its not required?

**Comment by fgregg** [comment]
You can get this behaviour with the --skip-training flag, relate to #46

**Comment by DaveKlassen4** [comment]
Actually you can't. If you look at the code the settings file is never written to disk.

**Comment by fgregg** [comment]
Woops!

**Comment by fgregg** [comment]
I think this would be a great idea. I don't have a lot of time to make the change now, but would be happy to see a pull request.

**Comment by DaveKlassen4** [comment]
My major issue here was trying to ensure somewhat predictable results given a specific configuration of learned training settings and data. With my datasets the information is growing, and I hope to re-run the commands and be able to update a list of pre-sorted results/clusters from prior runs. 

What I have found is that performing the training with just under a thousand previous training decisions, produces a fair amount of variable results, and in some cases the error ratio is much higher than other runs (with the exact same training inputs). Of course I cannot afford variable results for my reporting purposes, so I am really happy to pass this on to other people as well. I have a lot to learn here from the dedupe library, and am very grateful for this tool.
